<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EntradasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('entradas')->delete();
        
        \DB::table('entradas')->insert(array (
            0 => 
            array (
                'id' => 1,
                'articulo_id' => 1,
                'cantidad' => 82,
                'precio' => '2446.88',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            1 => 
            array (
                'id' => 2,
                'articulo_id' => 2,
                'cantidad' => 5336,
                'precio' => '13340.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            2 => 
            array (
                'id' => 3,
                'articulo_id' => 3,
                'cantidad' => 1032,
                'precio' => '2580.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            3 => 
            array (
                'id' => 4,
                'articulo_id' => 4,
                'cantidad' => 264,
                'precio' => '660.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            4 => 
            array (
                'id' => 5,
                'articulo_id' => 5,
                'cantidad' => 996,
                'precio' => '2490.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            5 => 
            array (
                'id' => 6,
                'articulo_id' => 6,
                'cantidad' => 204,
                'precio' => '510.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            6 => 
            array (
                'id' => 7,
                'articulo_id' => 7,
                'cantidad' => 36,
                'precio' => '90.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            7 => 
            array (
                'id' => 8,
                'articulo_id' => 8,
                'cantidad' => 59,
                'precio' => '295.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            8 => 
            array (
                'id' => 9,
                'articulo_id' => 10,
                'cantidad' => 136,
                'precio' => '4207.84',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            9 => 
            array (
                'id' => 10,
                'articulo_id' => 11,
                'cantidad' => 285,
                'precio' => '31595.10',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            10 => 
            array (
                'id' => 11,
                'articulo_id' => 17,
                'cantidad' => 32,
                'precio' => '330.56',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            11 => 
            array (
                'id' => 12,
                'articulo_id' => 18,
                'cantidad' => 25,
                'precio' => '326.75',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            12 => 
            array (
                'id' => 13,
                'articulo_id' => 21,
                'cantidad' => 3,
                'precio' => '115.35',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            13 => 
            array (
                'id' => 14,
                'articulo_id' => 22,
                'cantidad' => 9,
                'precio' => '346.05',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            14 => 
            array (
                'id' => 15,
                'articulo_id' => 23,
                'cantidad' => 2,
                'precio' => '101.30',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            15 => 
            array (
                'id' => 16,
                'articulo_id' => 24,
                'cantidad' => 1,
                'precio' => '72.60',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            16 => 
            array (
                'id' => 17,
                'articulo_id' => 26,
                'cantidad' => 6,
                'precio' => '439.80',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            17 => 
            array (
                'id' => 18,
                'articulo_id' => 27,
                'cantidad' => 3,
                'precio' => '852.75',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            18 => 
            array (
                'id' => 19,
                'articulo_id' => 29,
                'cantidad' => 6,
                'precio' => '279.90',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            19 => 
            array (
                'id' => 20,
                'articulo_id' => 30,
                'cantidad' => 158,
                'precio' => '804.22',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            20 => 
            array (
                'id' => 21,
                'articulo_id' => 31,
                'cantidad' => 27,
                'precio' => '962.55',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            21 => 
            array (
                'id' => 22,
                'articulo_id' => 33,
                'cantidad' => 100,
                'precio' => '3533.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            22 => 
            array (
                'id' => 23,
                'articulo_id' => 34,
                'cantidad' => 43,
                'precio' => '1190.24',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            23 => 
            array (
                'id' => 24,
                'articulo_id' => 35,
                'cantidad' => 66,
                'precio' => '3647.16',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            24 => 
            array (
                'id' => 25,
                'articulo_id' => 36,
                'cantidad' => 3,
                'precio' => '17.88',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            25 => 
            array (
                'id' => 26,
                'articulo_id' => 37,
                'cantidad' => 58,
                'precio' => '779.52',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            26 => 
            array (
                'id' => 27,
                'articulo_id' => 38,
                'cantidad' => 271,
                'precio' => '6853.59',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            27 => 
            array (
                'id' => 28,
                'articulo_id' => 39,
                'cantidad' => 70,
                'precio' => '504.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            28 => 
            array (
                'id' => 29,
                'articulo_id' => 40,
                'cantidad' => 87,
                'precio' => '746.46',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            29 => 
            array (
                'id' => 30,
                'articulo_id' => 41,
                'cantidad' => 63,
                'precio' => '885.15',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            30 => 
            array (
                'id' => 31,
                'articulo_id' => 42,
                'cantidad' => 32,
                'precio' => '639.36',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            31 => 
            array (
                'id' => 32,
                'articulo_id' => 43,
                'cantidad' => 147,
                'precio' => '8379.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            32 => 
            array (
                'id' => 33,
                'articulo_id' => 44,
                'cantidad' => 919,
                'precio' => '5082.07',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            33 => 
            array (
                'id' => 34,
                'articulo_id' => 45,
                'cantidad' => 100,
                'precio' => '2925.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            34 => 
            array (
                'id' => 35,
                'articulo_id' => 48,
                'cantidad' => 329,
                'precio' => '3122.21',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            35 => 
            array (
                'id' => 36,
                'articulo_id' => 49,
                'cantidad' => 103,
                'precio' => '874.47',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            36 => 
            array (
                'id' => 37,
                'articulo_id' => 50,
                'cantidad' => 675,
                'precio' => '337.50',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            37 => 
            array (
                'id' => 38,
                'articulo_id' => 51,
                'cantidad' => 54,
                'precio' => '17012.70',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            38 => 
            array (
                'id' => 39,
                'articulo_id' => 52,
                'cantidad' => 3,
                'precio' => '2569.38',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            39 => 
            array (
                'id' => 40,
                'articulo_id' => 53,
                'cantidad' => 53,
                'precio' => '9372.52',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            40 => 
            array (
                'id' => 41,
                'articulo_id' => 54,
                'cantidad' => 49,
                'precio' => '10296.37',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            41 => 
            array (
                'id' => 42,
                'articulo_id' => 56,
                'cantidad' => 546,
                'precio' => '2615.34',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            42 => 
            array (
                'id' => 43,
                'articulo_id' => 58,
                'cantidad' => 382,
                'precio' => '8545.34',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            43 => 
            array (
                'id' => 44,
                'articulo_id' => 60,
                'cantidad' => 82,
                'precio' => '3172.58',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            44 => 
            array (
                'id' => 45,
                'articulo_id' => 61,
                'cantidad' => 5,
                'precio' => '83.80',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            45 => 
            array (
                'id' => 46,
                'articulo_id' => 63,
                'cantidad' => 152,
                'precio' => '3204.16',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            46 => 
            array (
                'id' => 47,
                'articulo_id' => 64,
                'cantidad' => 882,
                'precio' => '2222.64',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            47 => 
            array (
                'id' => 48,
                'articulo_id' => 65,
                'cantidad' => 1000,
                'precio' => '2170.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            48 => 
            array (
                'id' => 49,
                'articulo_id' => 66,
                'cantidad' => 69,
                'precio' => '2085.87',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            49 => 
            array (
                'id' => 50,
                'articulo_id' => 68,
                'cantidad' => 76,
                'precio' => '1972.20',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            50 => 
            array (
                'id' => 51,
                'articulo_id' => 69,
                'cantidad' => 116,
                'precio' => '1200.60',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            51 => 
            array (
                'id' => 52,
                'articulo_id' => 70,
                'cantidad' => 49,
                'precio' => '9640.75',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            52 => 
            array (
                'id' => 53,
                'articulo_id' => 71,
                'cantidad' => 123,
                'precio' => '2063.94',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            53 => 
            array (
                'id' => 54,
                'articulo_id' => 72,
                'cantidad' => 64,
                'precio' => '1073.92',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            54 => 
            array (
                'id' => 55,
                'articulo_id' => 73,
                'cantidad' => 130,
                'precio' => '949.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            55 => 
            array (
                'id' => 56,
                'articulo_id' => 74,
                'cantidad' => 120,
                'precio' => '876.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            56 => 
            array (
                'id' => 57,
                'articulo_id' => 75,
                'cantidad' => 2,
                'precio' => '25.32',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            57 => 
            array (
                'id' => 58,
                'articulo_id' => 76,
                'cantidad' => 15,
                'precio' => '242.25',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            58 => 
            array (
                'id' => 59,
                'articulo_id' => 77,
                'cantidad' => 13,
                'precio' => '209.95',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            59 => 
            array (
                'id' => 60,
                'articulo_id' => 78,
                'cantidad' => 16,
                'precio' => '424.96',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            60 => 
            array (
                'id' => 61,
                'articulo_id' => 79,
                'cantidad' => 3730,
                'precio' => '306867.10',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            61 => 
            array (
                'id' => 62,
                'articulo_id' => 80,
                'cantidad' => 1770,
                'precio' => '149919.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            62 => 
            array (
                'id' => 63,
                'articulo_id' => 81,
                'cantidad' => 12,
                'precio' => '503.76',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            63 => 
            array (
                'id' => 64,
                'articulo_id' => 82,
                'cantidad' => 16,
                'precio' => '4310.72',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            64 => 
            array (
                'id' => 65,
                'articulo_id' => 84,
                'cantidad' => 283,
                'precio' => '1197.09',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            65 => 
            array (
                'id' => 66,
                'articulo_id' => 85,
                'cantidad' => 623,
                'precio' => '2635.29',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            66 => 
            array (
                'id' => 67,
                'articulo_id' => 86,
                'cantidad' => 168,
                'precio' => '710.64',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            67 => 
            array (
                'id' => 68,
                'articulo_id' => 87,
                'cantidad' => 370,
                'precio' => '1565.10',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            68 => 
            array (
                'id' => 69,
                'articulo_id' => 88,
                'cantidad' => 193,
                'precio' => '816.39',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            69 => 
            array (
                'id' => 70,
                'articulo_id' => 89,
                'cantidad' => 19,
                'precio' => '1676.56',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            70 => 
            array (
                'id' => 71,
                'articulo_id' => 90,
                'cantidad' => 142,
                'precio' => '1715.36',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            71 => 
            array (
                'id' => 72,
                'articulo_id' => 91,
                'cantidad' => 83,
                'precio' => '2569.68',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            72 => 
            array (
                'id' => 73,
                'articulo_id' => 92,
                'cantidad' => 89,
                'precio' => '3551.10',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            73 => 
            array (
                'id' => 74,
                'articulo_id' => 93,
                'cantidad' => 80,
                'precio' => '829.60',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            74 => 
            array (
                'id' => 75,
                'articulo_id' => 94,
                'cantidad' => 5400,
                'precio' => '126846.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            75 => 
            array (
                'id' => 76,
                'articulo_id' => 95,
                'cantidad' => 330,
                'precio' => '950.40',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            76 => 
            array (
                'id' => 77,
                'articulo_id' => 96,
                'cantidad' => 15,
                'precio' => '212.85',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            77 => 
            array (
                'id' => 78,
                'articulo_id' => 97,
                'cantidad' => 2,
                'precio' => '38.06',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            78 => 
            array (
                'id' => 79,
                'articulo_id' => 99,
                'cantidad' => 57,
                'precio' => '7050.33',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            79 => 
            array (
                'id' => 80,
                'articulo_id' => 100,
                'cantidad' => 71,
                'precio' => '11291.84',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            80 => 
            array (
                'id' => 81,
                'articulo_id' => 101,
                'cantidad' => 12,
                'precio' => '958.44',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            81 => 
            array (
                'id' => 82,
                'articulo_id' => 102,
                'cantidad' => 72,
                'precio' => '30767.76',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            82 => 
            array (
                'id' => 83,
                'articulo_id' => 103,
                'cantidad' => 274,
                'precio' => '238.38',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            83 => 
            array (
                'id' => 84,
                'articulo_id' => 104,
                'cantidad' => 6,
                'precio' => '130.98',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            84 => 
            array (
                'id' => 85,
                'articulo_id' => 106,
                'cantidad' => 91,
                'precio' => '5972.33',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            85 => 
            array (
                'id' => 86,
                'articulo_id' => 107,
                'cantidad' => 118,
                'precio' => '2139.34',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            86 => 
            array (
                'id' => 87,
                'articulo_id' => 108,
                'cantidad' => 2,
                'precio' => '36.26',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            87 => 
            array (
                'id' => 88,
                'articulo_id' => 119,
                'cantidad' => 703,
                'precio' => '11107.40',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            88 => 
            array (
                'id' => 89,
                'articulo_id' => 120,
                'cantidad' => 281,
                'precio' => '3484.40',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            89 => 
            array (
                'id' => 90,
                'articulo_id' => 152,
                'cantidad' => 18,
                'precio' => '19620.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            90 => 
            array (
                'id' => 91,
                'articulo_id' => 158,
                'cantidad' => 4,
                'precio' => '3520.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            91 => 
            array (
                'id' => 92,
                'articulo_id' => 159,
                'cantidad' => 4,
                'precio' => '3520.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            92 => 
            array (
                'id' => 93,
                'articulo_id' => 160,
                'cantidad' => 2,
                'precio' => '1760.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            93 => 
            array (
                'id' => 94,
                'articulo_id' => 161,
                'cantidad' => 2,
                'precio' => '1760.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            94 => 
            array (
                'id' => 95,
                'articulo_id' => 163,
                'cantidad' => 1,
                'precio' => '800.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            95 => 
            array (
                'id' => 96,
                'articulo_id' => 176,
                'cantidad' => 15,
                'precio' => '10125.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            96 => 
            array (
                'id' => 97,
                'articulo_id' => 189,
                'cantidad' => 1,
                'precio' => '1190.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            97 => 
            array (
                'id' => 98,
                'articulo_id' => 196,
                'cantidad' => 23,
                'precio' => '25070.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            98 => 
            array (
                'id' => 99,
                'articulo_id' => 198,
                'cantidad' => 2,
                'precio' => '1780.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            99 => 
            array (
                'id' => 100,
                'articulo_id' => 199,
                'cantidad' => 5,
                'precio' => '5450.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            100 => 
            array (
                'id' => 101,
                'articulo_id' => 261,
                'cantidad' => 7,
                'precio' => '7042.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            101 => 
            array (
                'id' => 102,
                'articulo_id' => 262,
                'cantidad' => 1,
                'precio' => '1006.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            102 => 
            array (
                'id' => 103,
                'articulo_id' => 263,
                'cantidad' => 3,
                'precio' => '3018.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            103 => 
            array (
                'id' => 104,
                'articulo_id' => 264,
                'cantidad' => 2,
                'precio' => '2012.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            104 => 
            array (
                'id' => 105,
                'articulo_id' => 265,
                'cantidad' => 4,
                'precio' => '2776.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            105 => 
            array (
                'id' => 106,
                'articulo_id' => 351,
                'cantidad' => 1,
                'precio' => '2356.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            106 => 
            array (
                'id' => 107,
                'articulo_id' => 352,
                'cantidad' => 1,
                'precio' => '3210.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            107 => 
            array (
                'id' => 108,
                'articulo_id' => 354,
                'cantidad' => 1,
                'precio' => '3210.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            108 => 
            array (
                'id' => 109,
                'articulo_id' => 361,
                'cantidad' => 2,
                'precio' => '3580.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            109 => 
            array (
                'id' => 110,
                'articulo_id' => 439,
                'cantidad' => 3,
                'precio' => '282.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            110 => 
            array (
                'id' => 111,
                'articulo_id' => 440,
                'cantidad' => 15,
                'precio' => '1380.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            111 => 
            array (
                'id' => 112,
                'articulo_id' => 441,
                'cantidad' => 32,
                'precio' => '2432.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            112 => 
            array (
                'id' => 113,
                'articulo_id' => 442,
                'cantidad' => 41,
                'precio' => '3116.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            113 => 
            array (
                'id' => 114,
                'articulo_id' => 443,
                'cantidad' => 30,
                'precio' => '2280.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            114 => 
            array (
                'id' => 115,
                'articulo_id' => 444,
                'cantidad' => 68,
                'precio' => '2006.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            115 => 
            array (
                'id' => 116,
                'articulo_id' => 445,
                'cantidad' => 31,
                'precio' => '1976.25',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            116 => 
            array (
                'id' => 117,
                'articulo_id' => 446,
                'cantidad' => 10,
                'precio' => '895.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            117 => 
            array (
                'id' => 118,
                'articulo_id' => 447,
                'cantidad' => 20,
                'precio' => '965.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            118 => 
            array (
                'id' => 119,
                'articulo_id' => 448,
                'cantidad' => 10,
                'precio' => '7100.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            119 => 
            array (
                'id' => 120,
                'articulo_id' => 449,
                'cantidad' => 33,
                'precio' => '5032.50',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            120 => 
            array (
                'id' => 121,
                'articulo_id' => 450,
                'cantidad' => 331,
                'precio' => '4465.19',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            121 => 
            array (
                'id' => 122,
                'articulo_id' => 451,
                'cantidad' => 22,
                'precio' => '2150.50',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            122 => 
            array (
                'id' => 123,
                'articulo_id' => 453,
                'cantidad' => 2,
                'precio' => '221.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            123 => 
            array (
                'id' => 124,
                'articulo_id' => 455,
                'cantidad' => 22,
                'precio' => '1419.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            124 => 
            array (
                'id' => 125,
                'articulo_id' => 456,
                'cantidad' => 12,
                'precio' => '1632.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            125 => 
            array (
                'id' => 126,
                'articulo_id' => 457,
                'cantidad' => 5,
                'precio' => '218.75',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            126 => 
            array (
                'id' => 127,
                'articulo_id' => 458,
                'cantidad' => 79,
                'precio' => '2765.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            127 => 
            array (
                'id' => 128,
                'articulo_id' => 459,
                'cantidad' => 6,
                'precio' => '178.50',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            128 => 
            array (
                'id' => 129,
                'articulo_id' => 460,
                'cantidad' => 344,
                'precio' => '29240.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            129 => 
            array (
                'id' => 130,
                'articulo_id' => 461,
                'cantidad' => 152,
                'precio' => '9766.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            130 => 
            array (
                'id' => 131,
                'articulo_id' => 462,
                'cantidad' => 59,
                'precio' => '5767.25',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            131 => 
            array (
                'id' => 132,
                'articulo_id' => 463,
                'cantidad' => 82,
                'precio' => '5576.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            132 => 
            array (
                'id' => 133,
                'articulo_id' => 464,
                'cantidad' => 360,
                'precio' => '8829.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            133 => 
            array (
                'id' => 134,
                'articulo_id' => 465,
                'cantidad' => 300,
                'precio' => '8085.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            134 => 
            array (
                'id' => 135,
                'articulo_id' => 466,
                'cantidad' => 46,
                'precio' => '3059.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            135 => 
            array (
                'id' => 136,
                'articulo_id' => 468,
                'cantidad' => 160,
                'precio' => '2246.40',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            136 => 
            array (
                'id' => 137,
                'articulo_id' => 469,
                'cantidad' => 11,
                'precio' => '855.25',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            137 => 
            array (
                'id' => 138,
                'articulo_id' => 470,
                'cantidad' => 360,
                'precio' => '5050.80',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            138 => 
            array (
                'id' => 139,
                'articulo_id' => 471,
                'cantidad' => 380,
                'precio' => '5510.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            139 => 
            array (
                'id' => 140,
                'articulo_id' => 472,
                'cantidad' => 173,
                'precio' => '2508.50',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            140 => 
            array (
                'id' => 141,
                'articulo_id' => 473,
                'cantidad' => 11,
                'precio' => '1221.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            141 => 
            array (
                'id' => 142,
                'articulo_id' => 474,
                'cantidad' => 20,
                'precio' => '1205.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            142 => 
            array (
                'id' => 143,
                'articulo_id' => 475,
                'cantidad' => 20,
                'precio' => '490.60',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            143 => 
            array (
                'id' => 144,
                'articulo_id' => 476,
                'cantidad' => 27,
                'precio' => '1127.25',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            144 => 
            array (
                'id' => 145,
                'articulo_id' => 477,
                'cantidad' => 199,
                'precio' => '19601.50',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            145 => 
            array (
                'id' => 146,
                'articulo_id' => 479,
                'cantidad' => 500,
                'precio' => '38500.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            146 => 
            array (
                'id' => 147,
                'articulo_id' => 480,
                'cantidad' => 383,
                'precio' => '6989.75',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            147 => 
            array (
                'id' => 148,
                'articulo_id' => 481,
                'cantidad' => 1,
                'precio' => '230.75',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            148 => 
            array (
                'id' => 149,
                'articulo_id' => 483,
                'cantidad' => 52,
                'precio' => '7059.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            149 => 
            array (
                'id' => 150,
                'articulo_id' => 484,
                'cantidad' => 5,
                'precio' => '823.75',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            150 => 
            array (
                'id' => 151,
                'articulo_id' => 485,
                'cantidad' => 175,
                'precio' => '15400.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            151 => 
            array (
                'id' => 152,
                'articulo_id' => 486,
                'cantidad' => 62,
                'precio' => '3627.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            152 => 
            array (
                'id' => 153,
                'articulo_id' => 487,
                'cantidad' => 103,
                'precio' => '8883.75',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            153 => 
            array (
                'id' => 154,
                'articulo_id' => 488,
                'cantidad' => 622,
                'precio' => '11973.50',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            154 => 
            array (
                'id' => 155,
                'articulo_id' => 490,
                'cantidad' => 27,
                'precio' => '3915.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            155 => 
            array (
                'id' => 156,
                'articulo_id' => 491,
                'cantidad' => 68,
                'precio' => '6018.00',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
            156 => 
            array (
                'id' => 157,
                'articulo_id' => 492,
                'cantidad' => 252,
                'precio' => '635.04',
                'origen' => 'compra',
                'descripcion' => 'Existencias al 28 de marzo de 2025',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2025-04-03 11:27:02',
                'updated_at' => '2025-04-03 11:27:02',
            ),
        ));
        
        
    }
}